import { Inter, Roboto } from "next/font/google"; 
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300","400","500"],
});

const inter = Inter ({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400"],
 
});


export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased`}
      >
        <Navbar className={`${inter.className}`}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
