import { Roboto } from "next/font/google"; 
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const inter = Inter ({
  subsets: ['latin'],
  weight: "400"
});


export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <Navbar className={`${inter.className}`}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
